### ISSUE TITLE
Compile list of places where comments can be made

### ISSUE THREAD

**Issue by mathcass** [Data4Democracy/lobbyist-blacklist#1]
I wanted to capture a bit of conversation that would be a good item to work on. From @j2kao in the Slack channel:

> Yeah, data sources are different for each comment campaign, and each one may have to be scraped differently. https://www.regulations.gov/ is probably a place to start (Federal stuff).

> You can also look at lists of state agencies (e.g., https://en.wikipedia.org/wiki/List_of_environmental_agencies_in_the_United_States) and look at the websites of each one to get a sense of whether they publish received comments online. That's a bit more annoying because each state is different (labratories of democracy and all that, I guess).

---

The first step might just be to write a little blurb for the README about the comment process and which sites serve as portals for federal comments. A bigger leap from that might be looking into whether there are common portals for some of the state-based comment systems. 

---

At any rate, I learned something from the Slack channel (namely, where the original FCC comments lived) that I didn't know and wanted to record.

**Comment by j2kao** [comment]
Thanks for pulling that out, Cass!

For now I think the google doc is the best place for them because folks can freely edit without someone (i.e. me, haha) blocking a pull request, particularly when we're in an initial 'storming' phase of the project. I don't want to make the google doc link public for the moment, though. :smiley: 

Additional note, the FCC comments are also available at:
https://www.fcc.gov/ecfs/
https://www.fcc.gov/ecfs/public-api-docs.html

In the first link, they even provided a nice zip file (presumably because of all the people overloading their servers).

**Comment by mathcass** [comment]
Perfect! I just added the comments here to the Google Doc (I'd forgotten about it! :man_facepalming: )

**Comment by j2kao** [comment]
:+1: :smile:
